FROM golang:1.25-alpine AS builder
WORKDIR /app

ARG VERSION=dev
ARG BUILD_TIME=unknown

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .

RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags "-s -w \
    -X github.com/Linka-masterskaya/zip-backend/internal/app.Version=${VERSION} \
    -X github.com/Linka-masterskaya/zip-backend/internal/app.BuildTime=${BUILD_TIME}" \
    -trimpath \
    -o /app/bin/server \
    ./cmd/server && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags "-s -w" \
    -trimpath \
    -o /app/bin/migrate \
    ./cmd/migrate && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags "-s -w" \
    -trimpath \
    -o /app/bin/rotate-crypto \
    ./cmd/rotate-crypto && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
    -ldflags "-s -w" \
    -trimpath \
    -o /app/bin/picturebank-seed \
    ./cmd/picturebank-seed

# Stage 2
FROM gcr.io/distroless/static-debian12

WORKDIR /app

COPY --from=builder /app/bin/server .
COPY --from=builder /app/bin/migrate .
COPY --from=builder /app/bin/rotate-crypto .
COPY --from=builder /app/bin/picturebank-seed .
COPY config/config.prod.yml /app/config/config.prod.yml

ENV CONFIG_PATH=config/config.prod.yml


EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["./server"]
