global:
  scrape_interval: 5s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "zip-backend-metrics"
    static_configs:
      - targets: ["zip-backend:9091"]
    metrics_path: "/metrics"

  - job_name: "backup-pushgateway"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]
