// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mock_service_test.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockauthServiceIface is a mock of authServiceIface interface.
type MockauthServiceIface struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceIfaceMockRecorder
	isgomock struct{}
}

// MockauthServiceIfaceMockRecorder is the mock recorder for MockauthServiceIface.
type MockauthServiceIfaceMockRecorder struct {
	mock *MockauthServiceIface
}

// NewMockauthServiceIface creates a new mock instance.
func NewMockauthServiceIface(ctrl *gomock.Controller) *MockauthServiceIface {
	mock := &MockauthServiceIface{ctrl: ctrl}
	mock.recorder = &MockauthServiceIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthServiceIface) EXPECT() *MockauthServiceIfaceMockRecorder {
	return m.recorder
}

// ForgotPassword mocks base method.
func (m *MockauthServiceIface) ForgotPassword(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPassword", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForgotPassword indicates an expected call of ForgotPassword.
func (mr *MockauthServiceIfaceMockRecorder) ForgotPassword(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPassword", reflect.TypeOf((*MockauthServiceIface)(nil).ForgotPassword), ctx, email)
}

// Login mocks base method.
func (m *MockauthServiceIface) Login(ctx context.Context, email, password string) (*LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockauthServiceIfaceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockauthServiceIface)(nil).Login), ctx, email, password)
}

// ResetPassword mocks base method.
func (m *MockauthServiceIface) ResetPassword(ctx context.Context, token, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, token, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockauthServiceIfaceMockRecorder) ResetPassword(ctx, token, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockauthServiceIface)(nil).ResetPassword), ctx, token, newPassword)
}

// resendEmail mocks base method.
func (m *MockauthServiceIface) resendEmail(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "resendEmail", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// resendEmail indicates an expected call of resendEmail.
func (mr *MockauthServiceIfaceMockRecorder) resendEmail(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "resendEmail", reflect.TypeOf((*MockauthServiceIface)(nil).resendEmail), ctx)
}

// verifyEmail mocks base method.
func (m *MockauthServiceIface) verifyEmail(ctx context.Context, verifyToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "verifyEmail", ctx, verifyToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// verifyEmail indicates an expected call of verifyEmail.
func (mr *MockauthServiceIfaceMockRecorder) verifyEmail(ctx, verifyToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "verifyEmail", reflect.TypeOf((*MockauthServiceIface)(nil).verifyEmail), ctx, verifyToken)
}
