// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mock_service_test.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	http "net/http"
	reflect "reflect"

	cache "github.com/Linka-masterskaya/zip-backend/internal/cache"
	config "github.com/Linka-masterskaya/zip-backend/internal/config"
	middleware "github.com/Linka-masterskaya/zip-backend/internal/middleware"
	gomock "go.uber.org/mock/gomock"
)

// MockauthServiceIface is a mock of authServiceIface interface.
type MockauthServiceIface struct {
	ctrl     *gomock.Controller
	recorder *MockauthServiceIfaceMockRecorder
	isgomock struct{}
}

// MockauthServiceIfaceMockRecorder is the mock recorder for MockauthServiceIface.
type MockauthServiceIfaceMockRecorder struct {
	mock *MockauthServiceIface
}

// NewMockauthServiceIface creates a new mock instance.
func NewMockauthServiceIface(ctrl *gomock.Controller) *MockauthServiceIface {
	mock := &MockauthServiceIface{ctrl: ctrl}
	mock.recorder = &MockauthServiceIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthServiceIface) EXPECT() *MockauthServiceIfaceMockRecorder {
	return m.recorder
}

// ForgotPassword mocks base method.
func (m *MockauthServiceIface) ForgotPassword(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPassword", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForgotPassword indicates an expected call of ForgotPassword.
func (mr *MockauthServiceIfaceMockRecorder) ForgotPassword(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPassword", reflect.TypeOf((*MockauthServiceIface)(nil).ForgotPassword), ctx, email)
}

// Login mocks base method.
func (m *MockauthServiceIface) Login(ctx context.Context, email, password string) (*LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockauthServiceIfaceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockauthServiceIface)(nil).Login), ctx, email, password)
}

// Logout mocks base method.
func (m *MockauthServiceIface) Logout(ctx context.Context, refreshToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, refreshToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockauthServiceIfaceMockRecorder) Logout(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockauthServiceIface)(nil).Logout), ctx, refreshToken)
}

// Refresh mocks base method.
func (m *MockauthServiceIface) Refresh(ctx context.Context, refreshToken string) (*LoginResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, refreshToken)
	ret0, _ := ret[0].(*LoginResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockauthServiceIfaceMockRecorder) Refresh(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockauthServiceIface)(nil).Refresh), ctx, refreshToken)
}

// Register mocks base method.
func (m *MockauthServiceIface) Register(ctx context.Context, req RegisterRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockauthServiceIfaceMockRecorder) Register(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockauthServiceIface)(nil).Register), ctx, req)
}

// ResetPassword mocks base method.
func (m *MockauthServiceIface) ResetPassword(ctx context.Context, token, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPassword", ctx, token, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPassword indicates an expected call of ResetPassword.
func (mr *MockauthServiceIfaceMockRecorder) ResetPassword(ctx, token, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPassword", reflect.TypeOf((*MockauthServiceIface)(nil).ResetPassword), ctx, token, newPassword)
}

// resendEmail mocks base method.
func (m *MockauthServiceIface) resendEmail(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "resendEmail", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// resendEmail indicates an expected call of resendEmail.
func (mr *MockauthServiceIfaceMockRecorder) resendEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "resendEmail", reflect.TypeOf((*MockauthServiceIface)(nil).resendEmail), ctx, email)
}

// verifyEmail mocks base method.
func (m *MockauthServiceIface) verifyEmail(ctx context.Context, verifyToken string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "verifyEmail", ctx, verifyToken)
	ret0, _ := ret[0].(error)
	return ret0
}

// verifyEmail indicates an expected call of verifyEmail.
func (mr *MockauthServiceIfaceMockRecorder) verifyEmail(ctx, verifyToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "verifyEmail", reflect.TypeOf((*MockauthServiceIface)(nil).verifyEmail), ctx, verifyToken)
}

// MockAuthHandlerInterface is a mock of AuthHandlerInterface interface.
type MockAuthHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthHandlerInterfaceMockRecorder is the mock recorder for MockAuthHandlerInterface.
type MockAuthHandlerInterfaceMockRecorder struct {
	mock *MockAuthHandlerInterface
}

// NewMockAuthHandlerInterface creates a new mock instance.
func NewMockAuthHandlerInterface(ctrl *gomock.Controller) *MockAuthHandlerInterface {
	mock := &MockAuthHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockAuthHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthHandlerInterface) EXPECT() *MockAuthHandlerInterfaceMockRecorder {
	return m.recorder
}

// RegisterRoutes mocks base method.
func (m *MockAuthHandlerInterface) RegisterRoutes(mux *http.ServeMux, authMW *middleware.AuthMW, cacheClient *cache.Client, cfg *config.Config, loginLimit, registerLimit, refreshLimit, forgotLimit, resetLimit, verifyResendLimit, verifyEmailLimit middleware.Middleware) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRoutes", mux, authMW, cacheClient, cfg, loginLimit, registerLimit, refreshLimit, forgotLimit, resetLimit, verifyResendLimit, verifyEmailLimit)
}

// RegisterRoutes indicates an expected call of RegisterRoutes.
func (mr *MockAuthHandlerInterfaceMockRecorder) RegisterRoutes(mux, authMW, cacheClient, cfg, loginLimit, registerLimit, refreshLimit, forgotLimit, resetLimit, verifyResendLimit, verifyEmailLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoutes", reflect.TypeOf((*MockAuthHandlerInterface)(nil).RegisterRoutes), mux, authMW, cacheClient, cfg, loginLimit, registerLimit, refreshLimit, forgotLimit, resetLimit, verifyResendLimit, verifyEmailLimit)
}
