// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/auth/service.go -destination=internal/auth/mock_repo_test.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"
	time "time"

	cache "github.com/Linka-masterskaya/zip-backend/internal/cache"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockauthRepoIface is a mock of authRepoIface interface.
type MockauthRepoIface struct {
	ctrl     *gomock.Controller
	recorder *MockauthRepoIfaceMockRecorder
	isgomock struct{}
}

// MockauthRepoIfaceMockRecorder is the mock recorder for MockauthRepoIface.
type MockauthRepoIfaceMockRecorder struct {
	mock *MockauthRepoIface
}

// NewMockauthRepoIface creates a new mock instance.
func NewMockauthRepoIface(ctrl *gomock.Controller) *MockauthRepoIface {
	mock := &MockauthRepoIface{ctrl: ctrl}
	mock.recorder = &MockauthRepoIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthRepoIface) EXPECT() *MockauthRepoIfaceMockRecorder {
	return m.recorder
}

// CreateAuthCred mocks base method.
func (m *MockauthRepoIface) CreateAuthCred(ctx context.Context, params CreateAuthCredParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthCred", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuthCred indicates an expected call of CreateAuthCred.
func (mr *MockauthRepoIfaceMockRecorder) CreateAuthCred(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthCred", reflect.TypeOf((*MockauthRepoIface)(nil).CreateAuthCred), ctx, params)
}

// CreateIdentity mocks base method.
func (m *MockauthRepoIface) CreateIdentity(ctx context.Context, identity *UserIdentity) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIdentity", ctx, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIdentity indicates an expected call of CreateIdentity.
func (mr *MockauthRepoIfaceMockRecorder) CreateIdentity(ctx, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIdentity", reflect.TypeOf((*MockauthRepoIface)(nil).CreateIdentity), ctx, identity)
}

// CreateOAuthUser mocks base method.
func (m *MockauthRepoIface) CreateOAuthUser(ctx context.Context, params CreateUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOAuthUser", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOAuthUser indicates an expected call of CreateOAuthUser.
func (mr *MockauthRepoIfaceMockRecorder) CreateOAuthUser(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOAuthUser", reflect.TypeOf((*MockauthRepoIface)(nil).CreateOAuthUser), ctx, params)
}

// CreatePasswordResetToken mocks base method.
func (m *MockauthRepoIface) CreatePasswordResetToken(ctx context.Context, userID string, ttl time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePasswordResetToken", ctx, userID, ttl)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePasswordResetToken indicates an expected call of CreatePasswordResetToken.
func (mr *MockauthRepoIfaceMockRecorder) CreatePasswordResetToken(ctx, userID, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePasswordResetToken", reflect.TypeOf((*MockauthRepoIface)(nil).CreatePasswordResetToken), ctx, userID, ttl)
}

// FindIdentityByProviderUID mocks base method.
func (m *MockauthRepoIface) FindIdentityByProviderUID(ctx context.Context, provider, providerUID string) (*UserIdentity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindIdentityByProviderUID", ctx, provider, providerUID)
	ret0, _ := ret[0].(*UserIdentity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindIdentityByProviderUID indicates an expected call of FindIdentityByProviderUID.
func (mr *MockauthRepoIfaceMockRecorder) FindIdentityByProviderUID(ctx, provider, providerUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindIdentityByProviderUID", reflect.TypeOf((*MockauthRepoIface)(nil).FindIdentityByProviderUID), ctx, provider, providerUID)
}

// GetAuthCredByUserID mocks base method.
func (m *MockauthRepoIface) GetAuthCredByUserID(ctx context.Context, userID uuid.UUID) (*UserCred, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthCredByUserID", ctx, userID)
	ret0, _ := ret[0].(*UserCred)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthCredByUserID indicates an expected call of GetAuthCredByUserID.
func (mr *MockauthRepoIfaceMockRecorder) GetAuthCredByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthCredByUserID", reflect.TypeOf((*MockauthRepoIface)(nil).GetAuthCredByUserID), ctx, userID)
}

// GetUserByEmailHash mocks base method.
func (m *MockauthRepoIface) GetUserByEmailHash(ctx context.Context, emailHash []byte) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmailHash", ctx, emailHash)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmailHash indicates an expected call of GetUserByEmailHash.
func (mr *MockauthRepoIfaceMockRecorder) GetUserByEmailHash(ctx, emailHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmailHash", reflect.TypeOf((*MockauthRepoIface)(nil).GetUserByEmailHash), ctx, emailHash)
}

// GetUserByID mocks base method.
func (m *MockauthRepoIface) GetUserByID(ctx context.Context, userID uuid.UUID) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockauthRepoIfaceMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockauthRepoIface)(nil).GetUserByID), ctx, userID)
}

// ResetPasswordByToken mocks base method.
func (m *MockauthRepoIface) ResetPasswordByToken(ctx context.Context, token, passwordHash string) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPasswordByToken", ctx, token, passwordHash)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetPasswordByToken indicates an expected call of ResetPasswordByToken.
func (mr *MockauthRepoIfaceMockRecorder) ResetPasswordByToken(ctx, token, passwordHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPasswordByToken", reflect.TypeOf((*MockauthRepoIface)(nil).ResetPasswordByToken), ctx, token, passwordHash)
}

// beginTx mocks base method.
func (m *MockauthRepoIface) beginTx(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "beginTx", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// beginTx indicates an expected call of beginTx.
func (mr *MockauthRepoIfaceMockRecorder) beginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "beginTx", reflect.TypeOf((*MockauthRepoIface)(nil).beginTx), ctx)
}

// rotateEmailTokens mocks base method.
func (m *MockauthRepoIface) rotateEmailTokens(ctx context.Context, tokenID, userID uuid.UUID, hash []byte, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "rotateEmailTokens", ctx, tokenID, userID, hash, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// rotateEmailTokens indicates an expected call of rotateEmailTokens.
func (mr *MockauthRepoIfaceMockRecorder) rotateEmailTokens(ctx, tokenID, userID, hash, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "rotateEmailTokens", reflect.TypeOf((*MockauthRepoIface)(nil).rotateEmailTokens), ctx, tokenID, userID, hash, expiresAt)
}

// useEmailVerifyToken mocks base method.
func (m *MockauthRepoIface) useEmailVerifyToken(ctx context.Context, token []byte) (uuid.UUID, uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "useEmailVerifyToken", ctx, token)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// useEmailVerifyToken indicates an expected call of useEmailVerifyToken.
func (mr *MockauthRepoIfaceMockRecorder) useEmailVerifyToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "useEmailVerifyToken", reflect.TypeOf((*MockauthRepoIface)(nil).useEmailVerifyToken), ctx, token)
}

// verifyStudent mocks base method.
func (m *MockauthRepoIface) verifyStudent(ctx context.Context, studentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "verifyStudent", ctx, studentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// verifyStudent indicates an expected call of verifyStudent.
func (mr *MockauthRepoIfaceMockRecorder) verifyStudent(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "verifyStudent", reflect.TypeOf((*MockauthRepoIface)(nil).verifyStudent), ctx, studentID)
}

// verifyUser mocks base method.
func (m *MockauthRepoIface) verifyUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "verifyUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// verifyUser indicates an expected call of verifyUser.
func (mr *MockauthRepoIfaceMockRecorder) verifyUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "verifyUser", reflect.TypeOf((*MockauthRepoIface)(nil).verifyUser), ctx, userID)
}

// withTx mocks base method.
func (m *MockauthRepoIface) withTx(tx pgx.Tx) authRepoIface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withTx", tx)
	ret0, _ := ret[0].(authRepoIface)
	return ret0
}

// withTx indicates an expected call of withTx.
func (mr *MockauthRepoIfaceMockRecorder) withTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withTx", reflect.TypeOf((*MockauthRepoIface)(nil).withTx), tx)
}

// MockrefreshStore is a mock of refreshStore interface.
type MockrefreshStore struct {
	ctrl     *gomock.Controller
	recorder *MockrefreshStoreMockRecorder
	isgomock struct{}
}

// MockrefreshStoreMockRecorder is the mock recorder for MockrefreshStore.
type MockrefreshStoreMockRecorder struct {
	mock *MockrefreshStore
}

// NewMockrefreshStore creates a new mock instance.
func NewMockrefreshStore(ctrl *gomock.Controller) *MockrefreshStore {
	mock := &MockrefreshStore{ctrl: ctrl}
	mock.recorder = &MockrefreshStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrefreshStore) EXPECT() *MockrefreshStoreMockRecorder {
	return m.recorder
}

// GetRefresh mocks base method.
func (m *MockrefreshStore) GetRefresh(ctx context.Context, jti string) (*cache.RefreshRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefresh", ctx, jti)
	ret0, _ := ret[0].(*cache.RefreshRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRefresh indicates an expected call of GetRefresh.
func (mr *MockrefreshStoreMockRecorder) GetRefresh(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefresh", reflect.TypeOf((*MockrefreshStore)(nil).GetRefresh), ctx, jti)
}

// IsFamilyRevoked mocks base method.
func (m *MockrefreshStore) IsFamilyRevoked(ctx context.Context, fid string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFamilyRevoked", ctx, fid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFamilyRevoked indicates an expected call of IsFamilyRevoked.
func (mr *MockrefreshStoreMockRecorder) IsFamilyRevoked(ctx, fid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFamilyRevoked", reflect.TypeOf((*MockrefreshStore)(nil).IsFamilyRevoked), ctx, fid)
}

// IsSessionRevoked mocks base method.
func (m *MockrefreshStore) IsSessionRevoked(ctx context.Context, rec cache.RefreshRecord) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSessionRevoked", ctx, rec)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSessionRevoked indicates an expected call of IsSessionRevoked.
func (mr *MockrefreshStoreMockRecorder) IsSessionRevoked(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSessionRevoked", reflect.TypeOf((*MockrefreshStore)(nil).IsSessionRevoked), ctx, rec)
}

// RevokeAllSessions mocks base method.
func (m *MockrefreshStore) RevokeAllSessions(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAllSessions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAllSessions indicates an expected call of RevokeAllSessions.
func (mr *MockrefreshStoreMockRecorder) RevokeAllSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAllSessions", reflect.TypeOf((*MockrefreshStore)(nil).RevokeAllSessions), ctx, userID)
}

// RevokeFamily mocks base method.
func (m *MockrefreshStore) RevokeFamily(ctx context.Context, fid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeFamily", ctx, fid)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeFamily indicates an expected call of RevokeFamily.
func (mr *MockrefreshStoreMockRecorder) RevokeFamily(ctx, fid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeFamily", reflect.TypeOf((*MockrefreshStore)(nil).RevokeFamily), ctx, fid)
}

// RotateRefresh mocks base method.
func (m *MockrefreshStore) RotateRefresh(ctx context.Context, req cache.RotateRefreshRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateRefresh", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateRefresh indicates an expected call of RotateRefresh.
func (mr *MockrefreshStoreMockRecorder) RotateRefresh(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateRefresh", reflect.TypeOf((*MockrefreshStore)(nil).RotateRefresh), ctx, req)
}

// StoreRefresh mocks base method.
func (m *MockrefreshStore) StoreRefresh(ctx context.Context, jti string, rec cache.RefreshRecord, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRefresh", ctx, jti, rec, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRefresh indicates an expected call of StoreRefresh.
func (mr *MockrefreshStoreMockRecorder) StoreRefresh(ctx, jti, rec, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRefresh", reflect.TypeOf((*MockrefreshStore)(nil).StoreRefresh), ctx, jti, rec, ttl)
}

// MockcryptoService is a mock of cryptoService interface.
type MockcryptoService struct {
	ctrl     *gomock.Controller
	recorder *MockcryptoServiceMockRecorder
	isgomock struct{}
}

// MockcryptoServiceMockRecorder is the mock recorder for MockcryptoService.
type MockcryptoServiceMockRecorder struct {
	mock *MockcryptoService
}

// NewMockcryptoService creates a new mock instance.
func NewMockcryptoService(ctrl *gomock.Controller) *MockcryptoService {
	mock := &MockcryptoService{ctrl: ctrl}
	mock.recorder = &MockcryptoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcryptoService) EXPECT() *MockcryptoServiceMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockcryptoService) Decrypt(ciphertext []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ciphertext)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockcryptoServiceMockRecorder) Decrypt(ciphertext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockcryptoService)(nil).Decrypt), ciphertext)
}

// Encrypt mocks base method.
func (m *MockcryptoService) Encrypt(plaintext []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plaintext)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockcryptoServiceMockRecorder) Encrypt(plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockcryptoService)(nil).Encrypt), plaintext)
}

// Hash mocks base method.
func (m *MockcryptoService) Hash(data []byte) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", data)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockcryptoServiceMockRecorder) Hash(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockcryptoService)(nil).Hash), data)
}
