// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock_repo_test.go -package=auth
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"
	time "time"

	cache "github.com/Linka-masterskaya/zip-backend/internal/cache"
	uuid "github.com/google/uuid"
	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockauthRepoIface is a mock of authRepoIface interface.
type MockauthRepoIface struct {
	ctrl     *gomock.Controller
	recorder *MockauthRepoIfaceMockRecorder
	isgomock struct{}
}

// MockauthRepoIfaceMockRecorder is the mock recorder for MockauthRepoIface.
type MockauthRepoIfaceMockRecorder struct {
	mock *MockauthRepoIface
}

// NewMockauthRepoIface creates a new mock instance.
func NewMockauthRepoIface(ctrl *gomock.Controller) *MockauthRepoIface {
	mock := &MockauthRepoIface{ctrl: ctrl}
	mock.recorder = &MockauthRepoIfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthRepoIface) EXPECT() *MockauthRepoIfaceMockRecorder {
	return m.recorder
}

// CreateAuthCred mocks base method.
func (m *MockauthRepoIface) CreateAuthCred(ctx context.Context, params CreateAuthCredParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthCred", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAuthCred indicates an expected call of CreateAuthCred.
func (mr *MockauthRepoIfaceMockRecorder) CreateAuthCred(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthCred", reflect.TypeOf((*MockauthRepoIface)(nil).CreateAuthCred), ctx, params)
}

// CreateOrganization mocks base method.
func (m *MockauthRepoIface) CreateOrganization(ctx context.Context, params CreateOrganizationParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrganization", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrganization indicates an expected call of CreateOrganization.
func (mr *MockauthRepoIfaceMockRecorder) CreateOrganization(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrganization", reflect.TypeOf((*MockauthRepoIface)(nil).CreateOrganization), ctx, params)
}

// CreateUser mocks base method.
func (m *MockauthRepoIface) CreateUser(ctx context.Context, params CreateUserParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockauthRepoIfaceMockRecorder) CreateUser(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockauthRepoIface)(nil).CreateUser), ctx, params)
}

// CreateVerifyToken mocks base method.
func (m *MockauthRepoIface) CreateVerifyToken(ctx context.Context, params CreateVerifyTokenParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerifyToken", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVerifyToken indicates an expected call of CreateVerifyToken.
func (mr *MockauthRepoIfaceMockRecorder) CreateVerifyToken(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerifyToken", reflect.TypeOf((*MockauthRepoIface)(nil).CreateVerifyToken), ctx, params)
}

// EmailExists mocks base method.
func (m *MockauthRepoIface) EmailExists(ctx context.Context, emailHash []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmailExists", ctx, emailHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmailExists indicates an expected call of EmailExists.
func (mr *MockauthRepoIfaceMockRecorder) EmailExists(ctx, emailHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmailExists", reflect.TypeOf((*MockauthRepoIface)(nil).EmailExists), ctx, emailHash)
}

// GetUserByEmailHash mocks base method.
func (m *MockauthRepoIface) GetUserByEmailHash(ctx context.Context, emailHash []byte) (*User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmailHash", ctx, emailHash)
	ret0, _ := ret[0].(*User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmailHash indicates an expected call of GetUserByEmailHash.
func (mr *MockauthRepoIfaceMockRecorder) GetUserByEmailHash(ctx, emailHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmailHash", reflect.TypeOf((*MockauthRepoIface)(nil).GetUserByEmailHash), ctx, emailHash)
}

// beginTx mocks base method.
func (m *MockauthRepoIface) beginTx(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "beginTx", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// beginTx indicates an expected call of beginTx.
func (mr *MockauthRepoIfaceMockRecorder) beginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "beginTx", reflect.TypeOf((*MockauthRepoIface)(nil).beginTx), ctx)
}

// getUserContactForResend mocks base method.
func (m *MockauthRepoIface) getUserContactForResend(ctx context.Context, userID uuid.UUID) ([]byte, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getUserContactForResend", ctx, userID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// getUserContactForResend indicates an expected call of getUserContactForResend.
func (mr *MockauthRepoIfaceMockRecorder) getUserContactForResend(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getUserContactForResend", reflect.TypeOf((*MockauthRepoIface)(nil).getUserContactForResend), ctx, userID)
}

// rotateEmailTokens mocks base method.
func (m *MockauthRepoIface) rotateEmailTokens(ctx context.Context, tokenID, userID uuid.UUID, hash []byte, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "rotateEmailTokens", ctx, tokenID, userID, hash, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// rotateEmailTokens indicates an expected call of rotateEmailTokens.
func (mr *MockauthRepoIfaceMockRecorder) rotateEmailTokens(ctx, tokenID, userID, hash, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "rotateEmailTokens", reflect.TypeOf((*MockauthRepoIface)(nil).rotateEmailTokens), ctx, tokenID, userID, hash, expiresAt)
}

// useEmailVerifyToken mocks base method.
func (m *MockauthRepoIface) useEmailVerifyToken(ctx context.Context, token []byte) (uuid.UUID, uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "useEmailVerifyToken", ctx, token)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// useEmailVerifyToken indicates an expected call of useEmailVerifyToken.
func (mr *MockauthRepoIfaceMockRecorder) useEmailVerifyToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "useEmailVerifyToken", reflect.TypeOf((*MockauthRepoIface)(nil).useEmailVerifyToken), ctx, token)
}

// verifyStudent mocks base method.
func (m *MockauthRepoIface) verifyStudent(ctx context.Context, studentID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "verifyStudent", ctx, studentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// verifyStudent indicates an expected call of verifyStudent.
func (mr *MockauthRepoIfaceMockRecorder) verifyStudent(ctx, studentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "verifyStudent", reflect.TypeOf((*MockauthRepoIface)(nil).verifyStudent), ctx, studentID)
}

// verifyUser mocks base method.
func (m *MockauthRepoIface) verifyUser(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "verifyUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// verifyUser indicates an expected call of verifyUser.
func (mr *MockauthRepoIfaceMockRecorder) verifyUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "verifyUser", reflect.TypeOf((*MockauthRepoIface)(nil).verifyUser), ctx, userID)
}

// withTx mocks base method.
func (m *MockauthRepoIface) withTx(tx pgx.Tx) authRepoIface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withTx", tx)
	ret0, _ := ret[0].(authRepoIface)
	return ret0
}

// withTx indicates an expected call of withTx.
func (mr *MockauthRepoIfaceMockRecorder) withTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withTx", reflect.TypeOf((*MockauthRepoIface)(nil).withTx), tx)
}

// MockrefreshStore is a mock of refreshStore interface.
type MockrefreshStore struct {
	ctrl     *gomock.Controller
	recorder *MockrefreshStoreMockRecorder
	isgomock struct{}
}

// MockrefreshStoreMockRecorder is the mock recorder for MockrefreshStore.
type MockrefreshStoreMockRecorder struct {
	mock *MockrefreshStore
}

// NewMockrefreshStore creates a new mock instance.
func NewMockrefreshStore(ctrl *gomock.Controller) *MockrefreshStore {
	mock := &MockrefreshStore{ctrl: ctrl}
	mock.recorder = &MockrefreshStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrefreshStore) EXPECT() *MockrefreshStoreMockRecorder {
	return m.recorder
}

// StoreRefresh mocks base method.
func (m *MockrefreshStore) StoreRefresh(ctx context.Context, jti string, rec cache.RefreshRecord, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreRefresh", ctx, jti, rec, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreRefresh indicates an expected call of StoreRefresh.
func (mr *MockrefreshStoreMockRecorder) StoreRefresh(ctx, jti, rec, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreRefresh", reflect.TypeOf((*MockrefreshStore)(nil).StoreRefresh), ctx, jti, rec, ttl)
}

// MockcryptoService is a mock of cryptoService interface.
type MockcryptoService struct {
	ctrl     *gomock.Controller
	recorder *MockcryptoServiceMockRecorder
	isgomock struct{}
}

// MockcryptoServiceMockRecorder is the mock recorder for MockcryptoService.
type MockcryptoServiceMockRecorder struct {
	mock *MockcryptoService
}

// NewMockcryptoService creates a new mock instance.
func NewMockcryptoService(ctrl *gomock.Controller) *MockcryptoService {
	mock := &MockcryptoService{ctrl: ctrl}
	mock.recorder = &MockcryptoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcryptoService) EXPECT() *MockcryptoServiceMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockcryptoService) Decrypt(ciphertext []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ciphertext)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockcryptoServiceMockRecorder) Decrypt(ciphertext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockcryptoService)(nil).Decrypt), ciphertext)
}

// Encrypt mocks base method.
func (m *MockcryptoService) Encrypt(plaintext []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plaintext)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockcryptoServiceMockRecorder) Encrypt(plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockcryptoService)(nil).Encrypt), plaintext)
}

// Hash mocks base method.
func (m *MockcryptoService) Hash(data []byte) []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", data)
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Hash indicates an expected call of Hash.
func (mr *MockcryptoServiceMockRecorder) Hash(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockcryptoService)(nil).Hash), data)
}
